use std::fmt::Write as _;
use std::path::Path;
use std::{env, fs};

mod prng {
    include!("src/prng.rs");
}

mod reference {
    include!("src/attacks/reference.rs");
}

use prng::Prng;
use reference::{bishop_attacks_slow, rook_attacks_slow};

const SEED: u64 = 0x9E37_79B9_7F4A_7C15;

/// Files A and H, ranks 1 and 8.
const EDGES: u64 = 0x8181_8181_8181_8181 | 0xFF00_0000_0000_00FF;

/// Squares that can block a rook on `sq`: its file and rank, without `sq`
/// itself nor the edge squares at their ends.
fn rook_mask(sq: usize) -> u64 {
    let (file, rank) = (sq % 8, sq / 8);
    let mut mask = 0;
    for r in (1..7).filter(|&r| r != rank) {
        mask |= 1 << (r * 8 + file);
    }
    for f in (1..7).filter(|&f| f != file) {
        mask |= 1 << (rank * 8 + f);
    }
    mask
}

/// Squares that can block a bishop on `sq`: a piece on the edge blocks
/// nothing beyond it.
fn bishop_mask(sq: usize) -> u64 {
    bishop_attacks_slow(sq, 0) & !EDGES
}

/// One square's magic, before the tables are concatenated.
struct Found {
    mask: u64,
    magic: u64,
    shift: u32,
    table: Vec<u64>,
}

/// Finds a magic for `sq` mapping every subset of `mask` to an index whose
/// entry holds its attacks, with constructive collisions only.
fn find_magic(sq: usize, mask: u64, attacks: fn(usize, u64) -> u64, prng: &mut Prng) -> Found {
    let bits = mask.count_ones();
    let size = 1 << bits;
    let shift = 64 - bits;

    let mut occupancies = Vec::with_capacity(size);
    let mut expected = Vec::with_capacity(size);
    // Carry-Rippler: enumerates every subset of `mask`, starting from empty.
    let mut subset = 0u64;
    loop {
        occupancies.push(subset);
        expected.push(attacks(sq, subset));
        subset = subset.wrapping_sub(mask) & mask;
        if subset == 0 {
            break;
        }
    }

    let mut table = vec![0; size];
    // `used[i] == attempt` marks entry `i` as filled during this attempt, so
    // nothing needs clearing between attempts.
    let mut used = vec![0u32; size];
    let mut attempt = 0;
    loop {
        // Sparse candidates (about 8 bits set) are far more likely to work.
        let magic = prng.next_u64() & prng.next_u64() & prng.next_u64();
        if (mask.wrapping_mul(magic) >> 56).count_ones() < 6 {
            continue;
        }
        attempt += 1;
        let ok = occupancies.iter().zip(&expected).all(|(&occ, &att)| {
            let index = (occ.wrapping_mul(magic) >> shift) as usize;
            if used[index] != attempt {
                used[index] = attempt;
                table[index] = att;
                true
            } else {
                table[index] == att
            }
        });
        if ok {
            return Found {
                mask,
                magic,
                shift,
                table,
            };
        }
    }
}

/// Appends `ENTRIES` and `TABLE` for one piece to `out`.
fn write_piece(
    out: &mut String,
    name: &str,
    mask: fn(usize) -> u64,
    attacks: fn(usize, u64) -> u64,
    prng: &mut Prng,
) {
    let found: Vec<Found> = (0..64)
        .map(|sq| find_magic(sq, mask(sq), attacks, prng))
        .collect();

    writeln!(
        out,
        "pub(super) static {name}_ENTRIES: [MagicEntry; 64] = ["
    )
    .unwrap();
    let mut offset = 0;
    for f in &found {
        writeln!(
            out,
            "    MagicEntry {{ mask: {:#018x}, magic: {:#018x}, shift: {}, offset: {} }},",
            f.mask, f.magic, f.shift, offset
        )
        .unwrap();
        offset += f.table.len();
    }
    writeln!(out, "];\n").unwrap();

    writeln!(out, "pub(super) static {name}_TABLE: [u64; {offset}] = [").unwrap();
    for chunk in found
        .iter()
        .flat_map(|f| &f.table)
        .collect::<Vec<_>>()
        .chunks(4)
    {
        out.push_str("   ");
        for att in chunk {
            write!(out, " {att:#018x},").unwrap();
        }
        out.push('\n');
    }
    writeln!(out, "];\n").unwrap();
}

fn main() {
    println!("cargo::rerun-if-changed=build.rs");
    println!("cargo::rerun-if-changed=src/prng.rs");
    println!("cargo::rerun-if-changed=src/attacks/reference.rs");

    let mut prng = Prng::new(SEED);
    let mut out = String::from("// Generated by build.rs, do not edit.\n\n");
    write_piece(&mut out, "ROOK", rook_mask, rook_attacks_slow, &mut prng);
    write_piece(
        &mut out,
        "BISHOP",
        bishop_mask,
        bishop_attacks_slow,
        &mut prng,
    );

    let path = Path::new(&env::var("OUT_DIR").unwrap()).join("magics.rs");
    fs::write(path, out).unwrap();
}
